#
# CustomHealth Configurations
# 
# This config file only contains the messages section, the food values are held in seperate files in the worlds folder
# 


# You can use color codes using the & symbol and a hexadecimal number (0 - f), e.g. &4 (red), &f (white)
# After every line break, you have to "reassign" the color again, otherwise it'll set it to white again
# Variables, you can always use:
#    <player> - Name of the source player (if it was the console, the name is "console")
#    <n> - line break
messages:
  
  no-permission: "&4You don't have the permission."
  
  # variables:
  #    <food> - food name
  item-not-edible: "&c<food> &4is not edible."
  not-a-food-item: "&c<food> &4is not a food item."
  
  # variables:
  #    <food> - food item
  #    <hearts> - hearts value
  #    <hunger> - hunger value
  #    <saturation> - saturation level
  #    <effects> - effects
  food-info: "&8Food: &c<food><n>&8Hearts: &c<hearts><n>&8Hunger: &c<hunger><n>&8Saturation: &c<saturation><n>&8Effects: &c<effects>"