name: CustomHealth
main: at.felixfritz.customhealth.CustomHealth
version: 0.5.1 Beta
author: felixfritz
website: http://dev.bukkit.org/server-mods/custom-health/

commands:
  chealth:
    usage: /<command>
    aliases: [customhealth, ch]

permissions:
  customhealth.commands.*:
    description: Use all /chealth commands.
    default: op
    children:
      customhealth.commands.info: true
      customhealth.commands.set: true
      customhealth.commands.plugin: true
      customhealth.commands.reset: true
      customhealth.commands.reload: true
      customhealth.commands.create: true

  customhealth.commands.info:
    description: Get health/food/effect value of a food item.
    default: op
  
  customhealth.commands.set:
    description: Set health/food/effect value of a food item.
    default: op
  
  customhealth.commands.plugin:
    description: Get informations about the plugin.
    default: op
  
  customhealth.commands.reset:
    description: Reset everything to the default value.
    default: op
  
  customhealth.commands.reload:
    description: Reload config.
    default: op
  
  customhealth.commands.create:
    description: Create new yml file.
    default: op